export const RECRUITER_DASH_REQUEST = "RECRUITER_DASH_REQ"
export const RECRUITER_DASH_SUCCESS = "RECRUITER_DASH_SUCCESS"
export const RECRUITER_DASH_FAILURE = "RECRUITER_DASH_FAILURE"

export const DASHBOARD_CANDIDATE_REQUEST = "DASHBOARD_CANDIDATE_REQUEST"
export const DASHBOARD_CANDIDATE_SUCCESS = "DASHBOARD_CANDIDATE_SUCCESS"
export const DASHBOARD_CANDIDATE_FAILURE = "DASHBOARD_CANDIDATE_FAILURE"

export const COMMENTS_REQUEST = "COMMENTS_REQUEST"
export const COMMENTS_SUCCESS = "COMMENTS_SUCCESS"
export const COMMENTS_FAILURE = "COMMENTS_FAILURE"
